name: Daily Digest Workflow 
on: 
  schedule:
    - cron: '0 3 * * *'

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Digest Agent
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} # Lấy từ GitHub Secrets
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} # Lấy
          MAIL: ${{ secrets.MAIL }} # Lấy từ GitHub Secrets
        run: python main.py